import type { FieldDefinition, FieldSchemaDocument, SeedDefinition } from './types.js'

function textField(
  key: string,
  label: string,
  options: Partial<FieldDefinition> = {},
): FieldDefinition {
  return {
    key,
    type: 'text',
    label,
    required: false,
    safetyRelevant: false,
    aiVisible: true,
    projected: false,
    maxLength: 500,
    ...options,
  }
}

function longtextField(
  key: string,
  label: string,
  options: Partial<FieldDefinition> = {},
): FieldDefinition {
  return {
    key,
    type: 'longtext',
    label,
    required: false,
    safetyRelevant: false,
    aiVisible: true,
    projected: false,
    maxLength: 4000,
    ...options,
  }
}

function selectField(
  key: string,
  label: string,
  options: { value: string; label: string }[],
  extras: Partial<FieldDefinition> = {},
): FieldDefinition {
  return {
    key,
    type: 'select',
    label,
    required: false,
    safetyRelevant: false,
    aiVisible: true,
    projected: false,
    options,
    ...extras,
  }
}

function multiselectField(
  key: string,
  label: string,
  options: { value: string; label: string }[],
  extras: Partial<FieldDefinition> = {},
): FieldDefinition {
  return {
    key,
    type: 'multiselect',
    label,
    required: false,
    safetyRelevant: false,
    aiVisible: true,
    projected: false,
    options,
    ...extras,
  }
}

function booleanField(
  key: string,
  label: string,
  extras: Partial<FieldDefinition> = {},
): FieldDefinition {
  return {
    key,
    type: 'boolean',
    label,
    required: false,
    safetyRelevant: false,
    aiVisible: true,
    projected: false,
    ...extras,
  }
}

function scaleField(
  key: string,
  label: string,
  max: number,
  extras: Partial<FieldDefinition> = {},
): FieldDefinition {
  const points = []
  for (let value = 0; value <= max; value += 1) {
    points.push({ value, label: String(value) })
  }
  return {
    key,
    type: 'scale',
    label,
    required: false,
    safetyRelevant: false,
    aiVisible: true,
    projected: false,
    min: 0,
    max,
    points,
    ...extras,
  }
}

function durationField(
  key: string,
  label: string,
  extras: Partial<FieldDefinition> = {},
): FieldDefinition {
  return {
    key,
    type: 'duration',
    label,
    required: false,
    safetyRelevant: false,
    aiVisible: true,
    projected: false,
    min: 0,
    max: 24 * 60,
    ...extras,
  }
}

function timeField(
  key: string,
  label: string,
  extras: Partial<FieldDefinition> = {},
): FieldDefinition {
  return {
    key,
    type: 'time',
    label,
    required: false,
    safetyRelevant: false,
    aiVisible: true,
    projected: false,
    ...extras,
  }
}

function dateField(
  key: string,
  label: string,
  extras: Partial<FieldDefinition> = {},
): FieldDefinition {
  return {
    key,
    type: 'date',
    label,
    required: false,
    safetyRelevant: false,
    aiVisible: true,
    projected: false,
    ...extras,
  }
}

function numberField(
  key: string,
  label: string,
  extras: Partial<FieldDefinition> = {},
): FieldDefinition {
  return {
    key,
    type: 'number',
    label,
    required: false,
    safetyRelevant: false,
    aiVisible: true,
    projected: false,
    ...extras,
  }
}

function sliderField(
  key: string,
  label: string,
  extras: Partial<FieldDefinition> = {},
): FieldDefinition {
  return {
    key,
    type: 'slider',
    label,
    required: false,
    safetyRelevant: false,
    aiVisible: true,
    projected: false,
    min: 0,
    max: 100,
    ...extras,
  }
}

const QUIZ_TOPICS = [
  'sleep need varies',
  'bed is for sleep',
  'clock watching',
  'catch-up sleep',
  'alcohol and sleep',
  'caffeine timing',
  'exercise timing',
  'naps',
  'worrying in bed',
  'sleep effort',
  'weekend lie-ins',
  'sleep quality vs quantity',
  'medication myths',
  'age and sleep',
  'blue light nuance',
  'wind-down value',
  'consistent rise time',
  'temporary sleepiness',
]

function quizFields(): FieldDefinition[] {
  const fields: FieldDefinition[] = []
  for (const [index, topic] of QUIZ_TOPICS.entries()) {
    const n = String(index + 1)
    fields.push(
      booleanField(`q${n}Answer`, `Item ${n}: ${topic}`, { required: true, projected: true }),
      longtextField(`q${n}Explanation`, `Explanation for item ${n}`, {
        required: false,
        aiVisible: true,
      }),
    )
  }
  return fields
}

export const SEED_DEFINITIONS: SeedDefinition[] = [
  {
    slug: 'wk.sleep-history',
    title: 'Sleep history',
    purpose: 'Capture the present pattern and history of the sleep problem.',
    chapterReference: 'ch5',
    repeatable: true,
    fields: [
      longtextField('presentPattern', 'Present sleep pattern', { required: true }),
      scaleField('qualityRating', 'Perceived sleep quality', 4, { projected: true }),
      longtextField('daytimeEffects', 'Daytime effects'),
      multiselectField(
        'impactAreas',
        'Areas of impact',
        [
          { value: 'work', label: 'Work' },
          { value: 'mood', label: 'Mood' },
          { value: 'relationships', label: 'Relationships' },
          { value: 'leisure', label: 'Leisure' },
        ],
        { projected: true, allowOther: true },
      ),
      longtextField('qualityOfLifeImpact', 'Quality of life impact'),
      selectField(
        'onsetPeriod',
        'When the problem began',
        [
          { value: 'lt_1m', label: 'Less than 1 month' },
          { value: '1_3m', label: '1–3 months' },
          { value: '3_6m', label: '3–6 months' },
          { value: '6_12m', label: '6–12 months' },
          { value: 'gt_1y', label: 'More than 1 year' },
        ],
        { projected: true },
      ),
      longtextField('previousPattern', 'Previous sleep pattern'),
      booleanField('familyHistory', 'Family history of similar sleep problems', {
        projected: true,
      }),
      longtextField('physicalHealth', 'Physical health notes', { safetyRelevant: true }),
      longtextField('mentalHealth', 'Mental health notes', { safetyRelevant: true }),
    ],
  },
  {
    slug: 'wk.typical-night-estimate',
    title: 'Typical night estimate',
    purpose: 'Pre-baseline estimate of a typical night, stored separately from the diary.',
    chapterReference: 'ch5',
    repeatable: false,
    fields: [
      timeField('bedTime', 'Bed time', { required: true, projected: true }),
      timeField('lightsOutTime', 'Lights out', { required: true, projected: true }),
      durationField('sleepOnsetLatencyMins', 'Time to fall asleep', {
        required: true,
        projected: true,
      }),
      numberField('awakeningsCount', 'Number of awakenings', { min: 0, max: 30, projected: true }),
      durationField('wasoMins', 'Time awake during the night', { projected: true }),
      timeField('finalWakeTime', 'Final wake time', { required: true, projected: true }),
      timeField('outOfBedTime', 'Out of bed time', { required: true, projected: true }),
      durationField('totalSleepMins', 'Estimated total sleep', { projected: true }),
      scaleField('restfulnessRating', 'Restfulness', 4, { projected: true }),
      scaleField('sleepQualityRating', 'Sleep quality', 4, { projected: true }),
    ],
  },
  {
    slug: 'wk.treatment-goals',
    title: 'Treatment goals',
    purpose: 'Versioned treatment goals linked to measurable outcomes.',
    chapterReference: 'ch5',
    repeatable: true,
    fields: [
      {
        key: 'goals',
        type: 'repeater',
        label: 'Goals',
        required: true,
        safetyRelevant: false,
        aiVisible: true,
        projected: true,
        minItems: 1,
        maxItems: 5,
        fields: [
          selectField(
            'category',
            'Category',
            [
              { value: 'more_sleep', label: 'More sleep' },
              { value: 'more_satisfying', label: 'More satisfying' },
              { value: 'more_restorative', label: 'More restorative' },
              { value: 'more_reliable', label: 'More reliable' },
              { value: 'more_normal', label: 'More normal for me' },
            ],
            { required: true, projected: true },
          ),
          textField('statement', 'Goal statement', { required: true }),
          longtextField('achievableCheck', 'Achievable check'),
          longtextField('acceptableCheck', 'Acceptable check'),
          selectField(
            'measurableBy',
            'Measurable by',
            [
              { value: 'diary_metric', label: 'Diary metric' },
              { value: 'rating', label: 'Rating' },
              { value: 'observation', label: 'Described observation' },
            ],
            { projected: true },
          ),
          numberField('targetValue', 'Target value', { projected: true }),
          textField('targetMetric', 'Target metric', { projected: true }),
        ],
      },
    ],
  },
  {
    slug: 'wk.readiness',
    title: 'Readiness',
    purpose: 'Stage of change and confidence without computing a readiness score.',
    chapterReference: 'ch5',
    repeatable: true,
    fields: [
      selectField(
        'stageOfChange',
        'Stage of change',
        [
          { value: 'not_thinking', label: 'Not thinking about it' },
          { value: 'thinking', label: 'Thinking about it' },
          { value: 'preparing', label: 'Preparing' },
          { value: 'making_changes', label: 'Making changes' },
          { value: 'maintaining', label: 'Maintaining' },
          { value: 'setback', label: 'Had a setback' },
        ],
        { required: true, projected: true },
      ),
      scaleField('confidence', 'Confidence', 10, { required: true, projected: true }),
      scaleField('importance', 'Importance', 10, { required: true, projected: true }),
      multiselectField(
        'obstacles',
        'Obstacles',
        [
          { value: 'time', label: 'Time' },
          { value: 'motivation', label: 'Motivation' },
          { value: 'shift_work', label: 'Shift work' },
          { value: 'family', label: 'Family' },
          { value: 'health', label: 'Health' },
          { value: 'previous_disappointment', label: 'Previous disappointment' },
        ],
        { allowOther: true, projected: true },
      ),
      textField('timeSetAside', 'Time set aside'),
      longtextField('previousAttempts', 'Previous attempts'),
    ],
  },
  {
    slug: 'wk.sleep-knowledge-quiz',
    title: 'Sleep knowledge quiz',
    purpose: 'Reflect on common sleep beliefs. Never framed as a pass mark.',
    chapterReference: 'ch6',
    repeatable: true,
    fields: quizFields(),
  },
  {
    slug: 'wk.thought-record',
    title: 'Thought record',
    purpose: 'Capture and rebalance a sleep-related thought.',
    chapterReference: 'ch6',
    repeatable: true,
    fields: [
      dateField('occurredOn', 'Date', { required: true, projected: true }),
      timeField('occurredAt', 'Time', { required: true }),
      longtextField('situation', 'Situation', { required: true }),
      longtextField('thought', 'Thought', { required: true, safetyRelevant: true }),
      longtextField('feelingBefore', 'Feeling before'),
      multiselectField(
        'feelingLabels',
        'Feeling labels',
        [
          { value: 'anxious', label: 'Anxious' },
          { value: 'frustrated', label: 'Frustrated' },
          { value: 'hopeless', label: 'Hopeless' },
          { value: 'angry', label: 'Angry' },
          { value: 'sad', label: 'Sad' },
          { value: 'worried', label: 'Worried' },
        ],
        { allowOther: true, projected: true },
      ),
      sliderField('intensityBefore', 'Intensity before', { projected: true }),
      longtextField('evidence', 'Evidence'),
      longtextField('balancedThought', 'Balanced thought'),
      longtextField('feelingAfter', 'Feeling after'),
      sliderField('intensityAfter', 'Intensity after', { projected: true }),
      longtextField('followUp', 'Follow-up'),
      selectField(
        'theme',
        'Theme',
        [
          { value: 'sleep_itself', label: 'Sleep itself' },
          { value: 'tomorrow', label: 'Tomorrow' },
          { value: 'health', label: 'Health' },
          { value: 'work', label: 'Work' },
          { value: 'family', label: 'Family' },
          { value: 'trivial', label: 'Trivial thoughts' },
        ],
        { allowOther: true, projected: true },
      ),
    ],
  },
  {
    slug: 'wk.caffeine-inventory',
    title: 'Caffeine inventory',
    purpose: 'List caffeine products and decisions about them.',
    chapterReference: 'ch7',
    repeatable: true,
    fields: [
      {
        key: 'products',
        type: 'repeater',
        label: 'Products',
        required: false,
        safetyRelevant: false,
        aiVisible: true,
        projected: true,
        minItems: 0,
        maxItems: 40,
        fields: [
          textField('name', 'Name', { required: true, projected: true }),
          selectField(
            'location',
            'Location',
            [
              { value: 'kitchen', label: 'Kitchen' },
              { value: 'fridge', label: 'Fridge' },
              { value: 'medicine_cabinet', label: 'Medicine cabinet' },
              { value: 'work', label: 'Work' },
              { value: 'other', label: 'Other' },
            ],
            { projected: true },
          ),
          numberField('servingsPerDay', 'Servings per day', { min: 0, max: 20, projected: true }),
          timeField('lastServingTime', 'Last serving time', { projected: true }),
          selectField(
            'decision',
            'Decision',
            [
              { value: 'keep', label: 'Keep' },
              { value: 'reduce', label: 'Reduce' },
              { value: 'move_earlier', label: 'Move earlier' },
              { value: 'replace', label: 'Replace with caffeine-free' },
              { value: 'stop', label: 'Stop' },
            ],
            { projected: true },
          ),
        ],
      },
    ],
  },
  {
    slug: 'wk.lifestyle-plan',
    title: 'Lifestyle plan',
    purpose: 'Plan changes across caffeine, nicotine, alcohol, diet and exercise.',
    chapterReference: 'ch7',
    repeatable: true,
    fields: [
      booleanField('caffeineApplicable', 'Caffeine section applicable', { projected: true }),
      longtextField('caffeineCurrentPattern', 'Caffeine current pattern'),
      longtextField('caffeineChangeIntended', 'Caffeine change intended'),
      dateField('caffeineStartDate', 'Caffeine start date'),
      textField('caffeineHowIWillKnow', 'Caffeine how I will know'),
      booleanField('nicotineApplicable', 'Nicotine section applicable', { projected: true }),
      longtextField('nicotineCurrentPattern', 'Nicotine current pattern'),
      longtextField('nicotineChangeIntended', 'Nicotine change intended'),
      booleanField('alcoholApplicable', 'Alcohol section applicable', { projected: true }),
      longtextField('alcoholCurrentPattern', 'Alcohol current pattern'),
      longtextField('alcoholChangeIntended', 'Alcohol change intended'),
      booleanField('dietApplicable', 'Diet section applicable', { projected: true }),
      longtextField('dietCurrentPattern', 'Diet current pattern'),
      longtextField('dietChangeIntended', 'Diet change intended'),
      booleanField('exerciseApplicable', 'Exercise section applicable', {
        projected: true,
        safetyRelevant: true,
      }),
      longtextField('exerciseCurrentPattern', 'Exercise current pattern'),
      longtextField('exerciseChangeIntended', 'Exercise change intended'),
    ],
  },
  {
    slug: 'wk.bedroom-environment',
    title: 'Bedroom environment',
    purpose: 'Plan bedroom changes across noise, temperature, air, light and bedding.',
    chapterReference: 'ch7',
    repeatable: true,
    fields: [
      longtextField('noiseCurrent', 'Noise — current situation'),
      longtextField('noisePlan', 'Noise — what I will try'),
      booleanField('noiseDone', 'Noise — done', { projected: true }),
      longtextField('temperatureCurrent', 'Temperature — current situation'),
      longtextField('temperaturePlan', 'Temperature — what I will try'),
      selectField(
        'bathTiming',
        'Bath timing',
        [
          { value: 'none', label: 'None' },
          { value: 'just_before', label: 'Just before bed' },
          { value: 'hour_before', label: 'About an hour before bed' },
        ],
        { projected: true },
      ),
      longtextField('airQualityCurrent', 'Air quality — current situation'),
      longtextField('airQualityPlan', 'Air quality — what I will try'),
      longtextField('lightingCurrent', 'Lighting — current situation'),
      longtextField('lightingPlan', 'Lighting — what I will try'),
      longtextField('mattressCurrent', 'Mattress and pillows — current situation'),
      longtextField('mattressPlan', 'Mattress and pillows — what I will try'),
    ],
  },
  {
    slug: 'wk.wind-down-plan',
    title: 'Wind-down plan',
    purpose: 'Ordered wind-down activities with anchors and reminders.',
    chapterReference: 'ch7',
    repeatable: true,
    fields: [
      {
        key: 'activities',
        type: 'ordered_list',
        label: 'Activities',
        required: true,
        safetyRelevant: false,
        aiVisible: true,
        projected: true,
        minItems: 1,
        maxItems: 12,
        fields: [
          textField('name', 'Name', { required: true, projected: true }),
          durationField('durationMins', 'Duration', { required: true, projected: true }),
          selectField(
            'anchorType',
            'Anchor type',
            [
              { value: 'relative_to_threshold', label: 'Relative to threshold' },
              { value: 'relative_to_bedtime', label: 'Relative to bedtime' },
              { value: 'absolute_time', label: 'Absolute time' },
            ],
            { required: true, projected: true },
          ),
          numberField('offsetMins', 'Offset minutes', { min: 0, max: 300 }),
          timeField('absoluteTime', 'Absolute time'),
          selectField(
            'repeat',
            'Repeat',
            [
              { value: 'every_night', label: 'Every night' },
              { value: 'weeknights', label: 'Weeknights' },
              { value: 'weekends', label: 'Weekends' },
              { value: 'custom', label: 'Custom days' },
            ],
            { projected: true },
          ),
          booleanField('flexible', 'Flexible', { projected: true }),
          booleanField('reminder', 'Reminder', { projected: true }),
        ],
      },
    ],
  },
  {
    slug: 'wk.relaxation-brainstorm',
    title: 'Relaxation brainstorm',
    purpose: 'Find enjoyable activities across active and passive quadrants.',
    chapterReference: 'ch7',
    repeatable: true,
    fields: [
      multiselectField(
        'physicallyActive',
        'Physically active',
        [
          { value: 'walk', label: 'Gentle walk' },
          { value: 'stretch', label: 'Stretching' },
          { value: 'garden', label: 'Gardening' },
          { value: 'housework', label: 'Light housework' },
        ],
        { allowOther: true, projected: true },
      ),
      multiselectField(
        'mentallyActive',
        'Mentally active',
        [
          { value: 'crossword', label: 'Crossword or puzzle' },
          { value: 'reading', label: 'Reading' },
          { value: 'planning', label: 'Gentle planning' },
          { value: 'craft', label: 'Craft or drawing' },
        ],
        { allowOther: true, projected: true },
      ),
      multiselectField(
        'physicallyPassive',
        'Physically passive',
        [
          { value: 'warm_bath', label: 'Warm bath or shower' },
          { value: 'breathing', label: 'Slow breathing' },
          { value: 'body_scan', label: 'Body scan' },
          { value: 'progressive_relaxation', label: 'Progressive muscle relaxation' },
        ],
        {
          allowOther: true,
          projected: true,
          helpText: 'Many people with insomnia find passive options hardest — start small.',
        },
      ),
      multiselectField(
        'mentallyPassive',
        'Mentally passive',
        [
          { value: 'music', label: 'Calm music' },
          { value: 'audio_story', label: 'Audio story' },
          { value: 'nature_sounds', label: 'Nature sounds' },
          { value: 'imagery', label: 'Calm imagery' },
        ],
        { allowOther: true, projected: true },
      ),
      longtextField('whatIWillTryFirst', 'What I will try first', { required: true }),
    ],
  },
  {
    slug: 'wk.relaxation-practice-log',
    title: 'Relaxation practice log',
    purpose: 'Track short relaxation practices through Week 3.',
    chapterReference: 'ch7',
    repeatable: true,
    fields: [
      dateField('practiceDate', 'Date', { required: true, projected: true }),
      selectField(
        'timeOfDay',
        'Time of day',
        [
          { value: 'morning', label: 'Morning' },
          { value: 'afternoon', label: 'Afternoon' },
          { value: 'evening', label: 'Evening' },
          { value: 'night', label: 'Night' },
        ],
        { required: true, projected: true },
      ),
      textField('methodUsed', 'Method used', { required: true, projected: true }),
      durationField('durationMins', 'Duration', { required: true, projected: true }),
      scaleField('relaxedBefore', 'How relaxed before', 10, { required: true, projected: true }),
      scaleField('relaxedAfter', 'How relaxed after', 10, { required: true, projected: true }),
      longtextField('notes', 'Notes'),
    ],
  },
  {
    slug: 'wk.bed-sleep-connection',
    title: 'Bed–sleep connection',
    purpose: 'Plan stimulus-control decisions for Week 4.',
    chapterReference: 'ch8',
    repeatable: true,
    fields: [
      longtextField('bedForSleepOnlyCurrent', 'Bed for sleep only — current'),
      longtextField('bedForSleepOnlyPlan', 'Bed for sleep only — my plan', { required: true }),
      longtextField('quarterHourRuleCurrent', 'Quarter-hour rule — current'),
      longtextField('quarterHourRulePlan', 'Quarter-hour rule — my plan', { required: true }),
      longtextField('goingToBedOnlyWhenSleepyCurrent', 'Go to bed only when sleepy — current'),
      longtextField('goingToBedOnlyWhenSleepyPlan', 'Go to bed only when sleepy — my plan', {
        required: true,
      }),
      longtextField('nappingCurrent', 'Napping — current'),
      longtextField('nappingPlan', 'Napping — my plan', { required: true }),
      multiselectField(
        'preparations',
        'Preparations',
        [
          { value: 'lamp_on', label: 'Lamp left on' },
          { value: 'heating_low', label: 'Heating low' },
          { value: 'warm_drink', label: 'Warm drink prepared' },
          { value: 'activity_chosen', label: 'Book or activity chosen' },
          { value: 'household_informed', label: 'Household informed' },
        ],
        { allowOther: true, projected: true },
      ),
    ],
  },
  {
    slug: 'wk.sleepiness-signs',
    title: 'Sleepiness signs',
    purpose: 'Distinguish sleepiness from tiredness.',
    chapterReference: 'ch8',
    repeatable: true,
    fields: [
      multiselectField(
        'signs',
        'Signs of sleepiness',
        [
          { value: 'itchy_eyes', label: 'Heavy or itchy eyes' },
          { value: 'yawning', label: 'Yawning' },
          { value: 'hard_to_follow', label: 'Difficulty following a page or programme' },
          { value: 'head_nodding', label: 'Head nodding' },
          { value: 'aching_muscles', label: 'Aching muscles' },
          { value: 'losing_thread', label: 'Losing the thread of thoughts' },
        ],
        { required: true, allowOther: true, projected: true },
      ),
      longtextField('whatTirednessFeelsLikeInstead', 'What tiredness feels like instead', {
        required: true,
      }),
    ],
  },
  {
    slug: 'wk.nap-plan',
    title: 'Nap plan',
    purpose: 'Decide how to handle naps during scheduling.',
    chapterReference: 'ch8',
    repeatable: true,
    fields: [
      booleanField('napsCurrently', 'I currently nap', { required: true, projected: true }),
      {
        key: 'naps',
        type: 'repeater',
        label: 'Current naps',
        required: false,
        safetyRelevant: true,
        aiVisible: true,
        projected: true,
        minItems: 0,
        maxItems: 10,
        fields: [
          timeField('time', 'Time', { projected: true }),
          durationField('durationMins', 'Duration', { projected: true }),
          textField('where', 'Where'),
          booleanField('intentional', 'Intentional', { projected: true, safetyRelevant: true }),
        ],
      },
      selectField(
        'plan',
        'Plan',
        [
          { value: 'stop', label: 'Stop napping' },
          { value: 'limit_short', label: 'Limit to one short nap' },
          { value: 'keep_with_reason', label: 'Keep as is with a reason' },
        ],
        { required: true, projected: true },
      ),
      longtextField('planDetail', 'Plan detail'),
    ],
  },
  {
    slug: 'wk.schedule-eligibility-ack',
    title: 'Schedule eligibility acknowledgement',
    purpose: 'Acknowledge named risks before creating a sleep schedule.',
    chapterReference: 'ch8',
    repeatable: true,
    fields: [
      {
        key: 'eligibilityOutcome',
        type: 'readonly_derived',
        label: 'Eligibility outcome',
        required: false,
        safetyRelevant: true,
        aiVisible: false,
        projected: true,
      },
      {
        key: 'reasonCodes',
        type: 'readonly_derived',
        label: 'Reason codes',
        required: false,
        safetyRelevant: true,
        aiVisible: false,
        projected: true,
      },
      booleanField('ackMayFeelSleepier', 'I may feel sleepier at first', {
        required: true,
        projected: true,
        safetyRelevant: true,
      }),
      booleanField('ackNoDrivingWhenSleepy', 'I will not drive or use machinery when sleepy', {
        required: true,
        projected: true,
        safetyRelevant: true,
      }),
      booleanField('ackKnowHowToPause', 'I know how to pause this', {
        required: true,
        projected: true,
        safetyRelevant: true,
      }),
      booleanField('ackNotMedicalAdvice', 'I know this is not medical advice', {
        required: true,
        projected: true,
        safetyRelevant: true,
      }),
      {
        key: 'policyVersion',
        type: 'readonly_derived',
        label: 'Policy version',
        required: false,
        safetyRelevant: false,
        aiVisible: false,
        projected: true,
      },
    ],
  },
  {
    slug: 'wk.schedule-adherence',
    title: 'Schedule adherence check-in',
    purpose: 'Daily adherence and sleepiness check-in during Week 4.',
    chapterReference: 'ch8',
    repeatable: true,
    fields: [
      dateField('checkinDate', 'Check-in date', { required: true, projected: true }),
      booleanField('stayedUpToThreshold', 'Stayed up to threshold time', { projected: true }),
      booleanField('bedOnlyWhenSleepy', 'Went to bed only when sleepy', { projected: true }),
      booleanField('bedForSleepOnly', 'Used bed for sleep only', { projected: true }),
      booleanField('gotUpWhenAwakeAWhile', 'Got up when awake a while', { projected: true }),
      booleanField('repeatedAsNeeded', 'Repeated as needed', { projected: true }),
      booleanField('gotUpAtRisingTime', 'Got up at rising time', { projected: true }),
      booleanField('avoidedNapping', 'Avoided napping', { projected: true }),
      booleanField('followedItToday', 'Followed the schedule today', { projected: true }),
      booleanField('somethingGotInTheWay', 'Something got in the way', { projected: true }),
      scaleField('sleepinessToday', 'Sleepiness today', 4, {
        required: true,
        projected: true,
        safetyRelevant: true,
      }),
      longtextField('notes', 'Notes'),
    ],
  },
  {
    slug: 'wk.weekly-schedule-review',
    title: 'Weekly schedule review',
    purpose: 'Review the week and decide on an extension, pause, or no change.',
    chapterReference: 'ch8',
    repeatable: true,
    fields: [
      dateField('weekStart', 'Week start', { required: true, projected: true }),
      dateField('weekEnd', 'Week end', { required: true, projected: true }),
      {
        key: 'nightsRecorded',
        type: 'readonly_derived',
        label: 'Nights recorded',
        required: false,
        safetyRelevant: false,
        aiVisible: false,
        projected: true,
      },
      {
        key: 'meanSleepEfficiency',
        type: 'readonly_derived',
        label: 'Mean sleep efficiency',
        required: false,
        safetyRelevant: false,
        aiVisible: false,
        projected: true,
      },
      {
        key: 'adherenceRate',
        type: 'readonly_derived',
        label: 'Adherence rate',
        required: false,
        safetyRelevant: false,
        aiVisible: false,
        projected: true,
      },
      {
        key: 'sleepinessTrend',
        type: 'readonly_derived',
        label: 'Sleepiness trend',
        required: false,
        safetyRelevant: true,
        aiVisible: false,
        projected: true,
      },
      {
        key: 'proposedChangeMinutes',
        type: 'readonly_derived',
        label: 'Proposed change minutes',
        required: false,
        safetyRelevant: false,
        aiVisible: false,
        projected: true,
      },
      selectField(
        'userDecision',
        'Decision',
        [
          { value: 'accept', label: 'Accept' },
          { value: 'decline', label: 'Decline' },
          { value: 'pause', label: 'Pause' },
          { value: 'ask_for_help', label: 'Ask for help' },
        ],
        { required: true, projected: true },
      ),
      longtextField('decisionNote', 'Decision note'),
    ],
  },
  {
    slug: 'wk.thought-content-profile',
    title: 'Thought content profile',
    purpose:
      'Interim reflection on night-time thought patterns (licence-flagged GCTI placeholder).',
    chapterReference: 'ch9',
    repeatable: true,
    instrumentKey: 'gcti',
    licenceStatus: 'flagged',
    featureFlagKey: 'instrument.gcti.enabled',
    fields: [
      selectField(
        'rehearsingPlanningFrequency',
        'Rehearsing and planning',
        [
          { value: 'never', label: 'Never' },
          { value: 'occasionally', label: 'Occasionally' },
          { value: 'often', label: 'Often' },
          { value: 'most_nights', label: 'Most nights' },
        ],
        { projected: true },
      ),
      longtextField('rehearsingPlanningExample', 'Example'),
      selectField(
        'problemSolvingFrequency',
        'Problem-solving',
        [
          { value: 'never', label: 'Never' },
          { value: 'occasionally', label: 'Occasionally' },
          { value: 'often', label: 'Often' },
          { value: 'most_nights', label: 'Most nights' },
        ],
        { projected: true },
      ),
      longtextField('problemSolvingExample', 'Example'),
      selectField(
        'thinkingAboutSleepFrequency',
        'Thinking about sleep',
        [
          { value: 'never', label: 'Never' },
          { value: 'occasionally', label: 'Occasionally' },
          { value: 'often', label: 'Often' },
          { value: 'most_nights', label: 'Most nights' },
        ],
        { projected: true },
      ),
      longtextField('thinkingAboutSleepExample', 'Example'),
      selectField(
        'monitoringBodyFrequency',
        'Monitoring bodily sensations',
        [
          { value: 'never', label: 'Never' },
          { value: 'occasionally', label: 'Occasionally' },
          { value: 'often', label: 'Often' },
          { value: 'most_nights', label: 'Most nights' },
        ],
        { projected: true },
      ),
      longtextField('monitoringBodyExample', 'Example'),
      selectField(
        'thinkingAboutThinkingFrequency',
        'Thinking about thinking',
        [
          { value: 'never', label: 'Never' },
          { value: 'occasionally', label: 'Occasionally' },
          { value: 'often', label: 'Often' },
          { value: 'most_nights', label: 'Most nights' },
        ],
        { projected: true },
      ),
      longtextField('thinkingAboutThinkingExample', 'Example'),
      selectField(
        'environmentalVigilanceFrequency',
        'Environmental vigilance',
        [
          { value: 'never', label: 'Never' },
          { value: 'occasionally', label: 'Occasionally' },
          { value: 'often', label: 'Often' },
          { value: 'most_nights', label: 'Most nights' },
        ],
        { projected: true },
      ),
      longtextField('environmentalVigilanceExample', 'Example'),
      selectField(
        'emotionsFrequency',
        'Emotions',
        [
          { value: 'never', label: 'Never' },
          { value: 'occasionally', label: 'Occasionally' },
          { value: 'often', label: 'Often' },
          { value: 'most_nights', label: 'Most nights' },
        ],
        { projected: true },
      ),
      longtextField('emotionsExample', 'Example'),
    ],
  },
  {
    slug: 'wk.putting-day-to-rest',
    title: 'Putting the day to rest',
    purpose: 'Park unfinished business before bed.',
    chapterReference: 'ch9',
    repeatable: true,
    fields: [
      longtextField('dayReflection', 'Day reflection', { required: true }),
      longtextField('whatFeltGood', 'What felt good'),
      longtextField('whatWasDifficult', 'What was difficult'),
      {
        key: 'toDo',
        type: 'repeater',
        label: 'To-do items',
        required: false,
        safetyRelevant: false,
        aiVisible: true,
        projected: false,
        minItems: 0,
        maxItems: 10,
        fields: [
          textField('task', 'Task', { required: true }),
          textField('firstStep', 'First step'),
          textField('when', 'When'),
        ],
      },
      longtextField('tomorrowSchedule', 'Tomorrow schedule'),
      {
        key: 'uncertainties',
        type: 'repeater',
        label: 'Uncertainties',
        required: false,
        safetyRelevant: false,
        aiVisible: true,
        projected: false,
        minItems: 0,
        maxItems: 10,
        fields: [
          textField('question', 'Question', { required: true }),
          textField('whenIWillFindOut', 'When I will find out'),
        ],
      },
      longtextField('closingReflection', 'Closing reflection'),
      {
        key: 'laterThoughts',
        type: 'repeater',
        label: 'Later bedside captures',
        required: false,
        safetyRelevant: false,
        aiVisible: true,
        projected: false,
        minItems: 0,
        maxItems: 20,
        fields: [
          textField('thought', 'Thought', { required: true, maxLength: 280 }),
          textField('capturedAt', 'Captured at'),
        ],
      },
    ],
  },
  {
    slug: 'wk.thought-blocking-log',
    title: 'Thought-blocking log',
    purpose: 'Record practice of thought-blocking.',
    chapterReference: 'ch9',
    repeatable: true,
    fields: [
      dateField('date', 'Date', { required: true, projected: true }),
      selectField(
        'context',
        'Context',
        [
          { value: 'settling', label: 'Settling' },
          { value: 'woke_in_night', label: 'Woke in the night' },
        ],
        { required: true, projected: true },
      ),
      durationField('durationMins', 'Duration', { projected: true }),
      scaleField('howItWent', 'How it went', 4, { required: true, projected: true }),
      longtextField('notes', 'Notes'),
    ],
  },
  {
    slug: 'wk.imagery-script',
    title: 'Imagery script',
    purpose: 'Build a calm personal imagery scene.',
    chapterReference: 'ch9',
    repeatable: true,
    fields: [
      textField('title', 'Title', { required: true, projected: true }),
      longtextField('setting', 'Setting', { required: true }),
      longtextField('sights', 'Sights'),
      longtextField('sounds', 'Sounds'),
      longtextField('smells', 'Smells'),
      longtextField('physicalSensations', 'Physical sensations'),
      {
        key: 'sequence',
        type: 'ordered_list',
        label: 'Scene sequence',
        required: true,
        safetyRelevant: false,
        aiVisible: true,
        projected: false,
        minItems: 1,
        maxItems: 12,
        fields: [textField('step', 'Step', { required: true })],
      },
      booleanField('calmnessCheck', 'This scene feels calming, not intense', {
        required: true,
        projected: true,
        safetyRelevant: true,
      }),
    ],
  },
  {
    slug: 'wk.imagery-practice-log',
    title: 'Imagery practice log',
    purpose: 'Track imagery practice sessions.',
    chapterReference: 'ch9',
    repeatable: true,
    fields: [
      dateField('date', 'Date', { required: true, projected: true }),
      selectField(
        'timeOfDay',
        'Time of day',
        [
          { value: 'day', label: 'Day' },
          { value: 'evening', label: 'Evening' },
          { value: 'night', label: 'Night' },
        ],
        { required: true, projected: true },
      ),
      scaleField('vividness', 'Vividness', 10, { required: true, projected: true }),
      scaleField('calmBefore', 'Calm before', 10, { projected: true }),
      scaleField('calmAfter', 'Calm after', 10, { projected: true }),
      booleanField('fellAsleepDuring', 'Fell asleep during practice', { projected: true }),
      longtextField('notes', 'Notes'),
    ],
  },
  {
    slug: 'wk.giving-up-trying',
    title: 'Giving up trying',
    purpose: 'Choose a method for reducing sleep effort.',
    chapterReference: 'ch9',
    repeatable: true,
    fields: [
      selectField(
        'methodChosen',
        'Method chosen',
        [
          {
            value: 'acceptance',
            label: 'Acceptance and a lighter perspective',
          },
          { value: 'gently_resisting', label: 'Gently resisting sleep' },
          { value: 'both', label: 'Both' },
        ],
        { required: true, projected: true },
      ),
      longtextField('whyThisMethod', 'Why this method', { required: true }),
      longtextField('myPlan', 'My plan', { required: true }),
      longtextField('whatWorstCaseActuallyIs', 'What the worst case actually is'),
      longtextField('reviewAfterAWeek', 'Review after a week'),
    ],
  },
  {
    slug: 'wk.sleep-effort',
    title: 'Sleep effort reflection',
    purpose: 'Interim unscored reflection on sleep effort (licence-flagged GSES placeholder).',
    chapterReference: 'ch9',
    repeatable: true,
    instrumentKey: 'gses',
    licenceStatus: 'flagged',
    featureFlagKey: 'instrument.gses.enabled',
    fields: [
      longtextField(
        'eveningPreoccupation',
        'How much of the evening is spent thinking about sleep',
        {
          required: true,
        },
      ),
      booleanField('sleepFeelsLikeAchievement', 'Sleep feels like something to achieve', {
        required: true,
        projected: true,
      }),
      longtextField('whatTryingLooksLike', 'What trying looks like in practice', {
        required: true,
      }),
      longtextField('whatIWantToLoosen', 'What I want to loosen'),
    ],
  },
  {
    slug: 'wk.clock-watching-chain',
    title: 'Clock-watching chain',
    purpose: 'Map daytime memories of clock-watching chains — never during the night.',
    chapterReference: 'ch9',
    repeatable: true,
    fields: [
      {
        key: 'chains',
        type: 'repeater',
        label: 'Chains',
        required: true,
        safetyRelevant: false,
        aiVisible: true,
        projected: false,
        minItems: 1,
        maxItems: 5,
        fields: [
          textField('clockReading', 'Clock reading recalled', { required: true }),
          longtextField('automaticThought', 'Automatic thought', { required: true }),
          longtextField('selfEvaluation', 'Self-evaluation'),
          longtextField('feeling', 'Feeling'),
          sliderField('intensity', 'Intensity', { min: 0, max: 100 }),
          longtextField('reframe', 'Reframe'),
        ],
      },
      selectField(
        'chosenResponse',
        'Chosen response',
        [
          { value: 'remove_clock', label: 'Remove the clock' },
          { value: 'turn_away', label: 'Turn it away' },
          { value: 'keep_and_reframe', label: 'Keep it and change what it means' },
        ],
        { required: true, projected: true },
      ),
      longtextField('plan', 'Plan', { required: true }),
    ],
  },
  {
    slug: 'wk.implementation-audit',
    title: 'Implementation audit',
    purpose: 'Review which programme components you are applying.',
    chapterReference: 'ch10',
    repeatable: true,
    fields: [
      dateField('auditDate', 'Audit date', { required: true, projected: true }),
      selectField(
        'basics',
        'Basics',
        [
          { value: 'consistently', label: 'Consistently applying' },
          { value: 'sometimes', label: 'Sometimes applying' },
          { value: 'not_yet', label: 'Not yet applying' },
          { value: 'not_applicable', label: 'Not applicable' },
          { value: 'paused', label: 'Paused for safety or clinical advice' },
        ],
        { required: true, projected: true },
      ),
      selectField(
        'beforeBed',
        'Before bed',
        [
          { value: 'consistently', label: 'Consistently applying' },
          { value: 'sometimes', label: 'Sometimes applying' },
          { value: 'not_yet', label: 'Not yet applying' },
          { value: 'not_applicable', label: 'Not applicable' },
          { value: 'paused', label: 'Paused for safety or clinical advice' },
        ],
        { required: true, projected: true },
      ),
      selectField(
        'atBedtime',
        'At bedtime',
        [
          { value: 'consistently', label: 'Consistently applying' },
          { value: 'sometimes', label: 'Sometimes applying' },
          { value: 'not_yet', label: 'Not yet applying' },
          { value: 'not_applicable', label: 'Not applicable' },
          { value: 'paused', label: 'Paused for safety or clinical advice' },
        ],
        { required: true, projected: true },
      ),
      selectField(
        'ifCannotSleep',
        'If you cannot sleep',
        [
          { value: 'consistently', label: 'Consistently applying' },
          { value: 'sometimes', label: 'Sometimes applying' },
          { value: 'not_yet', label: 'Not yet applying' },
          { value: 'not_applicable', label: 'Not applicable' },
          { value: 'paused', label: 'Paused for safety or clinical advice' },
        ],
        { required: true, projected: true },
      ),
      multiselectField(
        'hardestParts',
        'Hardest parts',
        [
          { value: 'basics', label: 'Basics' },
          { value: 'before_bed', label: 'Before bed' },
          { value: 'at_bedtime', label: 'At bedtime' },
          { value: 'if_cannot_sleep', label: 'If you cannot sleep' },
        ],
        { projected: true },
      ),
      longtextField('plan', 'Plan', { required: true }),
    ],
  },
  {
    slug: 'wk.progress-comparison',
    title: 'Progress comparison',
    purpose: 'Reflect on diary-derived progress over time.',
    chapterReference: 'ch10',
    repeatable: true,
    fields: [
      {
        key: 'sleepOnsetLatency',
        type: 'readonly_derived',
        label: 'Sleep-onset latency',
        required: false,
        safetyRelevant: false,
        aiVisible: false,
        projected: true,
      },
      {
        key: 'awakenings',
        type: 'readonly_derived',
        label: 'Number of awakenings',
        required: false,
        safetyRelevant: false,
        aiVisible: false,
        projected: true,
      },
      {
        key: 'wakeAfterSleepOnset',
        type: 'readonly_derived',
        label: 'Wake after sleep onset',
        required: false,
        safetyRelevant: false,
        aiVisible: false,
        projected: true,
      },
      {
        key: 'totalSleepTime',
        type: 'readonly_derived',
        label: 'Total sleep time',
        required: false,
        safetyRelevant: false,
        aiVisible: false,
        projected: true,
      },
      {
        key: 'timeInBed',
        type: 'readonly_derived',
        label: 'Time in bed',
        required: false,
        safetyRelevant: false,
        aiVisible: false,
        projected: true,
      },
      {
        key: 'sleepEfficiency',
        type: 'readonly_derived',
        label: 'Sleep efficiency',
        required: false,
        safetyRelevant: false,
        aiVisible: false,
        projected: true,
      },
      longtextField('reflection', 'Reflection', { required: true }),
    ],
  },
  {
    slug: 'wk.maintenance-goals',
    title: 'Maintenance goals',
    purpose: 'Decide what to keep going after the programme.',
    chapterReference: 'ch10',
    repeatable: true,
    fields: [
      {
        key: 'goals',
        type: 'repeater',
        label: 'Goals',
        required: true,
        safetyRelevant: false,
        aiVisible: true,
        projected: false,
        minItems: 1,
        maxItems: 5,
        fields: [
          textField('statement', 'Statement', { required: true }),
          selectField(
            'linkedComponent',
            'Linked component',
            [
              { value: 'basics', label: 'Basics' },
              { value: 'before_bed', label: 'Before bed' },
              { value: 'at_bedtime', label: 'At bedtime' },
              { value: 'if_cannot_sleep', label: 'If you cannot sleep' },
              { value: 'schedule', label: 'Schedule' },
            ],
            { required: true },
          ),
          longtextField('howIWillKeepItGoing', 'How I will keep it going', { required: true }),
          dateField('reviewDate', 'Review date'),
        ],
      },
    ],
  },
  {
    slug: 'wk.improvement-goals',
    title: 'Improvement goals',
    purpose: 'Choose what to strengthen next.',
    chapterReference: 'ch10',
    repeatable: true,
    fields: [
      {
        key: 'goals',
        type: 'repeater',
        label: 'Goals',
        required: true,
        safetyRelevant: false,
        aiVisible: true,
        projected: false,
        minItems: 1,
        maxItems: 5,
        fields: [
          textField('statement', 'Statement', { required: true }),
          selectField(
            'linkedComponent',
            'Linked component',
            [
              { value: 'basics', label: 'Basics' },
              { value: 'before_bed', label: 'Before bed' },
              { value: 'at_bedtime', label: 'At bedtime' },
              { value: 'if_cannot_sleep', label: 'If you cannot sleep' },
              { value: 'schedule', label: 'Schedule' },
            ],
            { required: true },
          ),
          longtextField('whatIWillTry', 'What I will try', { required: true }),
          dateField('reviewDate', 'Review date'),
        ],
      },
    ],
  },
  {
    slug: 'wk.wellbeing-reflection',
    title: 'Wellbeing reflection',
    purpose: 'Reflect on daytime wellbeing alongside sleep.',
    chapterReference: 'ch10',
    repeatable: true,
    fields: [
      scaleField('concentration', 'Concentration', 10, { required: true, projected: true }),
      longtextField('concentrationNotes', 'Concentration notes'),
      scaleField('mood', 'Mood', 10, { required: true, projected: true }),
      longtextField('moodNotes', 'Mood notes'),
      scaleField('energy', 'Energy', 10, { required: true, projected: true }),
      longtextField('energyNotes', 'Energy notes'),
      scaleField('productivity', 'Productivity', 10, { required: true, projected: true }),
      longtextField('productivityNotes', 'Productivity notes'),
      scaleField('qualityOfLife', 'Quality of life', 10, { required: true, projected: true }),
      longtextField('qualityOfLifeNotes', 'Quality of life notes'),
      longtextField('overallReflection', 'Overall reflection', { required: true }),
    ],
  },
  {
    slug: 'wk.relapse-prevention',
    title: 'Relapse prevention',
    purpose: 'Plan for setbacks without catastrophising.',
    chapterReference: 'ch10',
    repeatable: true,
    fields: [
      multiselectField(
        'expectedTriggers',
        'Expected triggers',
        [
          { value: 'stress', label: 'Stress' },
          { value: 'travel', label: 'Travel' },
          { value: 'illness', label: 'Illness' },
          { value: 'work_change', label: 'A change at work' },
          { value: 'bad_nights', label: 'A run of bad nights' },
        ],
        { allowOther: true, required: true, projected: true },
      ),
      longtextField('earlyWarningSigns', 'Early warning signs', { required: true }),
      {
        key: 'firstThingsToReinstate',
        type: 'ordered_list',
        label: 'First things to reinstate',
        required: true,
        safetyRelevant: false,
        aiVisible: true,
        projected: false,
        minItems: 1,
        maxItems: 8,
        fields: [
          selectField(
            'component',
            'Component',
            [
              { value: 'basics', label: 'Basics' },
              { value: 'before_bed', label: 'Before bed' },
              { value: 'at_bedtime', label: 'At bedtime' },
              { value: 'if_cannot_sleep', label: 'If you cannot sleep' },
              { value: 'schedule', label: 'Schedule' },
            ],
            { required: true },
          ),
        ],
      },
      textField('whoIWillTell', 'Who I will tell'),
      longtextField('whenIWouldSeekHelp', 'When I would seek help', { required: true }),
    ],
  },
  {
    slug: 'wk.booster-plan',
    title: 'Booster plan',
    purpose: 'Schedule future refresh points.',
    chapterReference: 'ch10',
    repeatable: true,
    fields: [
      {
        key: 'boosterDates',
        type: 'repeater',
        label: 'Booster dates',
        required: true,
        safetyRelevant: false,
        aiVisible: true,
        projected: false,
        minItems: 1,
        maxItems: 6,
        fields: [
          dateField('date', 'Date', { required: true }),
          multiselectField(
            'componentsToRefresh',
            'Components to refresh',
            [
              { value: 'basics', label: 'Basics' },
              { value: 'before_bed', label: 'Before bed' },
              { value: 'at_bedtime', label: 'At bedtime' },
              { value: 'if_cannot_sleep', label: 'If you cannot sleep' },
              { value: 'schedule', label: 'Schedule' },
            ],
            { required: true },
          ),
        ],
      },
      multiselectField(
        'followUpCheckpoints',
        'Follow-up checkpoints',
        [
          { value: '1_month', label: '1 month' },
          { value: '3_months', label: '3 months' },
          { value: '6_months', label: '6 months' },
          { value: '12_months', label: '12 months' },
        ],
        { projected: true },
      ),
    ],
  },
  {
    slug: 'wk.medication-log',
    title: 'Medication log',
    purpose: 'Personal record of sleep medication use — not medical instruction.',
    chapterReference: 'ch11',
    repeatable: true,
    fields: [
      dateField('date', 'Date', { required: true, projected: true }),
      textField('medicationName', 'Medication name', { required: true, projected: true }),
      textField('doseAsRecorded', 'Dose as recorded', {
        helpText: 'Free text only. This app never validates dosage.',
      }),
      timeField('timeTaken', 'Time taken', { projected: true }),
      booleanField('prescribed', 'Prescribed', { projected: true }),
      longtextField('notes', 'Notes'),
    ],
  },
  {
    slug: 'wk.prescriber-discussion-prep',
    title: 'Prescriber discussion prep',
    purpose: 'Prepare questions for a conversation with your prescriber.',
    chapterReference: 'ch11',
    repeatable: true,
    fields: [
      longtextField('whatITake', 'What I take', { required: true }),
      longtextField('howLong', 'How long', { required: true }),
      longtextField('whatIHaveNoticed', 'What I have noticed', { required: true }),
      {
        key: 'myQuestions',
        type: 'repeater',
        label: 'My questions',
        required: false,
        safetyRelevant: false,
        aiVisible: true,
        projected: false,
        minItems: 0,
        maxItems: 12,
        fields: [textField('question', 'Question', { required: true })],
      },
      longtextField('whatIWouldLikeToAsk', 'What I would like to ask'),
    ],
  },
  {
    slug: 'wk.other-disorders-recheck',
    title: 'Other sleep disorders recheck',
    purpose: 'Re-check features that may warrant a clinician conversation.',
    chapterReference: 'ch12',
    repeatable: true,
    fields: [
      booleanField('bodyClockConcern', 'Body-clock pattern concerns me', { projected: true }),
      booleanField('breathingPauses', 'Witnessed breathing pauses', {
        projected: true,
        safetyRelevant: true,
      }),
      booleanField('gaspingOrChoking', 'Gasping or choking during sleep', {
        projected: true,
        safetyRelevant: true,
      }),
      booleanField('restlessLegs', 'Restless legs or kicking', { projected: true }),
      booleanField('parasomniaInjuryRisk', 'Acting out dreams or injury risk', {
        projected: true,
        safetyRelevant: true,
      }),
      booleanField('sleepAttacks', 'Sleep attacks or collapse with emotion', {
        projected: true,
        safetyRelevant: true,
      }),
      booleanField('fallenAsleepDriving', 'Fallen asleep while driving', {
        projected: true,
        safetyRelevant: true,
      }),
      booleanField('healthNeedsAttentionFirst', 'Another health issue needs attention first', {
        projected: true,
      }),
      longtextField('notes', 'Notes'),
    ],
  },
]

export function toFieldSchema(definition: SeedDefinition): FieldSchemaDocument {
  return {
    version: '1',
    fields: definition.fields,
  }
}
