import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  await knex.raw('CREATE EXTENSION IF NOT EXISTS pgcrypto')
  await knex.raw('CREATE EXTENSION IF NOT EXISTS citext')

  await knex.schema.createTable('users', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
    table.specificType('email', 'citext').notNullable().unique()
    table.text('password_hash').notNullable()
    table.text('display_name').notNullable()
    table.text('time_zone').notNullable().defaultTo('Europe/London')
    table.text('theme').notNullable().defaultTo('system')
    table.text('diary_mode').notNullable().defaultTo('simple')
    table.boolean('health_sync_enabled').notNullable().defaultTo(false)
    table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
    table.timestamp('updated_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('refresh_tokens', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
    table.uuid('user_id').notNullable().references('id').inTable('users').onDelete('CASCADE')
    table.text('token_hash').notNullable().unique()
    table.timestamp('expires_at', { useTz: true }).notNullable()
    table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('sleep_nights', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
    table.uuid('user_id').notNullable().references('id').inTable('users').onDelete('CASCADE')
    table.date('night_date').notNullable()
    table.text('time_zone').notNullable()
    table.text('source').notNullable().defaultTo('manual')
    table.text('confirmation_state').notNullable().defaultTo('confirmed')
    table.text('bed_time')
    table.text('lights_out_time')
    table.integer('sleep_onset_latency_mins')
    table.integer('awakenings_count')
    table.integer('waso_mins')
    table.text('final_wake_time')
    table.text('out_of_bed_time')
    table.integer('total_sleep_mins')
    table.integer('early_morning_awake_mins')
    table.decimal('alcohol_units', 4, 1)
    table.boolean('sleep_medication_taken')
    table.text('sleep_medication_name')
    table.text('sleep_medication_dose')
    table.integer('restfulness_rating')
    table.integer('sleep_quality_rating')
    table.jsonb('factors').notNullable().defaultTo('[]')
    table.text('notes')
    table.text('notes_html')
    table.jsonb('health_intervals').notNullable().defaultTo('[]')
    table.jsonb('metrics').notNullable().defaultTo('{}')
    table.timestamp('health_synced_at', { useTz: true })
    table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
    table.timestamp('updated_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
    table.unique(['user_id', 'night_date'])
  })

  await knex.schema.createTable('sleep_plans', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
    table.uuid('user_id').notNullable().references('id').inTable('users').onDelete('CASCADE')
    table.text('status').notNullable().defaultTo('draft')
    table.text('rising_time').notNullable()
    table.text('threshold_time').notNullable()
    table.integer('window_minutes').notNullable()
    table.boolean('link_ios_sleep_schedule').notNullable().defaultTo(true)
    table.boolean('ack_may_feel_sleepier').notNullable().defaultTo(false)
    table.boolean('ack_no_driving_when_sleepy').notNullable().defaultTo(false)
    table.boolean('ack_not_medical_advice').notNullable().defaultTo(false)
    table.text('notes')
    table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
    table.timestamp('updated_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('plan_checkins', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
    table.uuid('user_id').notNullable().references('id').inTable('users').onDelete('CASCADE')
    table.uuid('plan_id').notNullable().references('id').inTable('sleep_plans').onDelete('CASCADE')
    table.date('checkin_date').notNullable()
    table.boolean('stayed_up_to_threshold')
    table.boolean('bed_only_when_sleepy')
    table.boolean('got_up_at_rising_time')
    table.boolean('followed_it_today')
    table.integer('sleepiness_today')
    table.text('notes')
    table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
    table.unique(['user_id', 'checkin_date'])
  })

  await knex.schema.createTable('chat_threads', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
    table.uuid('user_id').notNullable().references('id').inTable('users').onDelete('CASCADE')
    table.text('title').notNullable().defaultTo('Sleep coach')
    table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
    table.timestamp('updated_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('chat_messages', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
    table
      .uuid('thread_id')
      .notNullable()
      .references('id')
      .inTable('chat_threads')
      .onDelete('CASCADE')
    table.uuid('user_id').notNullable().references('id').inTable('users').onDelete('CASCADE')
    table.text('role').notNullable()
    table.text('content').notNullable()
    table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('sleep_analyses', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
    table.uuid('user_id').notNullable().references('id').inTable('users').onDelete('CASCADE')
    table.date('night_date').notNullable()
    table.text('headline').notNullable()
    table.text('body').notNullable()
    table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
  })

  await knex.schema.createTable('worksheet_entries', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
    table.uuid('user_id').notNullable().references('id').inTable('users').onDelete('CASCADE')
    table.text('definition_slug').notNullable()
    table.text('status').notNullable().defaultTo('draft')
    table.jsonb('responses').notNullable().defaultTo('{}')
    table.timestamp('submitted_at', { useTz: true })
    table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
    table.timestamp('updated_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
  })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('worksheet_entries')
  await knex.schema.dropTableIfExists('sleep_analyses')
  await knex.schema.dropTableIfExists('chat_messages')
  await knex.schema.dropTableIfExists('chat_threads')
  await knex.schema.dropTableIfExists('plan_checkins')
  await knex.schema.dropTableIfExists('sleep_plans')
  await knex.schema.dropTableIfExists('sleep_nights')
  await knex.schema.dropTableIfExists('refresh_tokens')
  await knex.schema.dropTableIfExists('users')
}
